kind: Service
apiVersion: v1
metadata:
  name: alfoldi322
  labels:
    app: alfoldi322
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31200
  selector:
    app: alfoldi322